# Generated by Django 4.1.7 on 2023-03-18 15:19

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_image_image'),
    ]

    operations = [
    migrations.AddField(
            model_name='Image',
            name='Image',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),

    ]
